version: '3.8'

services:  
  app:    
    build:      
      context: .      
      dockerfile: DockerFile.prod
    ports:
      - "3500:3000"    
    depends_on:      
      - db
    env_file:
      - .env.prod     
  db:
    image: postgres:12.3-alpine
    env_file:
      - .env.prod    
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db:
  db_data: