version: '3.8'

services:  
  app:    
    build:      
      context: .      
      dockerfile: DockerFile.prod
    ports:
      - "3500:3000"    
    depends_on:      
      - db
    env_file:
      - .env.prod     
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    env_file:
      - .env.prod
    ports:
      - '3400:3400'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local