version: '3.8'

services:  
  app:    
    build:      
      context: .      
      dockerfile: DockerFile.dev
    ports:
      - "3550:3000"    
    depends_on:      
      - db
    env_file:
      - .env.dev     
  db:
    image: postgres:12.3-alpine
    env_file:
      - .env.dev    
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db:
  db_data: