default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV["REAL_STATE_DATABASE_HOST"] %>
  database: <%= ENV["REAL_STATE_DATABASE_NAME"] %>
  username: <%= ENV["REAL_STATE_DATABASE_USERNAME"] %>
  password: <%= ENV["REAL_STATE_DATABASE_PASSWORD"] %>

test:
  <<: *default
  host: <%= ENV["REAL_STATE_DATABASE_HOST"] %>
  database: <%= ENV["REAL_STATE_DATABASE_NAME"] %>
  username: <%= ENV["REAL_STATE_DATABASE_USERNAME"] %>
  password: <%= ENV["REAL_STATE_DATABASE_PASSWORD"] %>

production:
  <<: *default
  host: <%= ENV["REAL_STATE_DATABASE_HOST"] %>
  database: <%= ENV["REAL_STATE_DATABASE_NAME"] %>
  username: <%= ENV["REAL_STATE_DATABASE_USERNAME"] %>
  password: <%= ENV["REAL_STATE_DATABASE_PASSWORD"] %>
